package:
    name: jungfrau_utils
    version: 0.0.1
source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyzmq

build:
  number: 1
  entry_points:
    - jungfrau_convert_gainmaps = jungfrau_utils.scripts.jungfrau_convert_gainmaps:main
    - jungfrau_run_pedestals = jungfrau_utils.scripts.jungfrau_run_pedestals:main

#about:
#    home: https://github.com/datastreaming/mflow
#    summary: "mflow library."